name: wallppib
version: '1.1.1'
summary: wallppib - A wallpaper changer for Linux
description: |
  wallppib is a wallpaper changer for Linux.

confinement: strict
base: core20

apps:
  myapp:
    command: usr/local/bin/wallppib
    environment:
      LD_LIBRARY_PATH: $SNAP/usr/lib:$SNAP/usr/lib/x86_64-linux-gnu:$SNAP/lib/x86_64-linux-gnu
    plugs:
      - desktop
      - desktop-legacy

parts:
  nlohmann-json:
    plugin: dump
    source: https://github.com/nlohmann/json/archive/refs/tags/v3.11.2.tar.gz
    source-type: tar
    organize:
      json-3.11.2/single_include/nlohmann: include/nlohmann

  myapp:
    plugin: cmake
    source: https://github.com/pekaala/wallppib.git
    build-packages:
      - build-essential
      - cmake
      - pkg-config
      - libgtk-3-dev
      - libgtkmm-3.0-dev
      - libopencv-dev
      - libmagick++-dev
      - libx11-dev
    stage-packages:
      - libgtk-3-0
      - libx11-6
      - libmagick++-6.q16-8
      - libopencv-core4.2
      - libopencv-imgproc4.2
      - libopencv-imgcodecs4.2
      - libgtkmm-3.0-1v5
      - libatkmm-1.6-1v5
      - libcairomm-1.0-1v5
      - libglibmm-2.4-1v5
      - libpangomm-1.4-1v5
      - libsigc++-2.0-0v5
      - libblas3
      - libblas-dev
    after:
      - nlohmann-json
    build-environment:
      - CXXFLAGS: '-I${SNAPCRAFT_STAGE}/include'
